Vagrant.configure("2") do |c|
  c.vm.box = "ros-web-dev-ubuntu-14.04-0.1.1"
  c.vm.box_url = "https://ros-chef.s3.amazonaws.com/vagrant/boxes/ros-web-dev-vm-ubuntu-14.04-0.1.1.box"
  c.vm.hostname = "ros-web-dev"
  c.vm.network(:forwarded_port, {:guest=>9090, :host=>9090})
  c.vm.network(:forwarded_port, {:guest=>8081, :host=>8081})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.memory = 1024
  end
end
