---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 9090, host: 9090}]
    - ["forwarded_port", {guest: 8081, host: 8081}]
  vm_hostname: 'ros-web-dev'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ros-web-dev::default]
      - recipe[ros-web-dev::rwt_dev_setup]
      - recipe[ros-web-dev::angular_ros]
    attributes:
      ros:
        #flavor: ros-base
        flavor: desktop-full
